# Generated by Django 3.2.7 on 2021-11-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='book',
        ),
    ]
