# Generated by Django 3.2.7 on 2021-10-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGenre', models.CharField(max_length=30)),
            ],
        ),
    ]
