# Generated by Django 3.2.8 on 2021-11-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0002_book_sinopsis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Sinopsis',
        ),
    ]
