# Generated by Django 3.2.7 on 2021-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='imageUrl',
            field=models.CharField(default='DEAULT VALUE', max_length=200),
        ),
    ]
