# Generated by Django 3.2.8 on 2021-12-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0003_auto_20211104_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
