# Generated by Django 3.2.8 on 2021-10-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0003_genre_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Background_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
