# Generated by Django 3.2.8 on 2021-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0004_book_background_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
