# Generated by Django 3.2.8 on 2021-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mancay', '0005_alter_book_background_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Background_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
