# Generated by Django 3.2.8 on 2021-10-27 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mancay', '0003_genre_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_rec', models.ManyToManyField(to='mancay.Book')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_books', models.ManyToManyField(to='mancay.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_interest', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Historical', 'Historical'), ('Biography', 'Biography'), ('Self-Development', 'Self-Development'), ('Business', 'Business')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('member_since', models.DateField(default=datetime.date(2021, 10, 27))),
                ('profile_pic', models.ImageField(upload_to='')),
                ('user_books_rec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fina.booksrec')),
                ('user_fav_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fina.favoritebook')),
                ('user_interest', models.ManyToManyField(to='fina.Interest')),
            ],
        ),
    ]
