# Generated by Django 3.2.8 on 2021-10-31 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Historical', 'Historical'), ('Biography', 'Biography'), ('Self-Development', 'Self-Development'), ('Business', 'Business')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_since',
            field=models.DateField(default=datetime.date(2021, 10, 31)),
        ),
    ]
