# Generated by Django 3.2.8 on 2021-10-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_since',
            field=models.DateField(default=datetime.date(2021, 10, 28)),
        ),
    ]
