# Generated by Django 3.2.8 on 2021-10-29 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0002_alter_user_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_since',
            field=models.DateField(default=datetime.date(2021, 10, 29)),
        ),
    ]
