# Generated by Django 3.2.8 on 2021-10-29 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0002_auto_20211028_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='user',
            name='member_since',
            field=models.DateField(default=datetime.date(2021, 10, 29)),
        ),
    ]
