# Generated by Django 3.2.8 on 2021-11-03 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0003_alter_profile_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_since',
            field=models.DateField(default=datetime.date(2021, 11, 3)),
        ),
    ]
