# Generated by Django 3.2.8 on 2021-10-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0003_auto_20211029_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_books_rec',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fina.booksrec'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_fav_book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fina.favoritebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fina.profilepic'),
        ),
    ]
