# Generated by Django 3.2.8 on 2021-10-29 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fina', '0004_auto_20211029_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('member_since', models.DateField(default=datetime.date(2021, 10, 29))),
                ('profile_pic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fina.profilepic')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_books_rec', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fina.booksrec')),
                ('user_fav_book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fina.favoritebook')),
                ('user_interest', models.ManyToManyField(to='fina.Interest')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
