# Generated by Django 3.2.8 on 2021-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0005_auto_20211029_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
