# Generated by Django 3.2.8 on 2021-10-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fina', '0006_auto_20211029_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebook',
            name='fav_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_books_rec',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_fav_book',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_interest',
        ),
        migrations.DeleteModel(
            name='BooksRec',
        ),
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
